Description of computefr
Home > computefr > computefr.m
computefr
PURPOSE
COMPUTEFR computes the firing rate from a strf and a song
SYNOPSIS
function [fr,spec] = computefr(songname,strffull)
DESCRIPTION
COMPUTEFR computes the firing rate from a strf and a song
   FR = COMPUTEFR(songname, strfname)
   Returns the firing rate obtaing from songname and strfname
CROSS-REFERENCE INFORMATION
This function calls:
getfr getfr.m
getsong GETSONG.M - Read song file
getsongspec getsongspec.m
This function is called by: