Description of srf_gabor_fun
Home > . > srf_gabor_fun.m
srf_gabor_fun
PURPOSE
SRF_GABOR_FUN : Gabor function for modeling of the Spectral Receptive Field.
SYNOPSIS
function FITGABOR = srf_gabor_fun(x,xdata)
DESCRIPTION
 SRF_GABOR_FUN : Gabor function for modeling of the Spectral Receptive Field.
                 fitgabor = SRF_GABOR_FUN(x,xdata)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
gabor_srf_model GABOR_SRF_MODEL : Least-Squares Modeling of SRF data.
gabor_trf_model GABOR_SRF_MODEL : Least-Squares Modeling of TRF data.
sfitstrf SFITSTRF: Spectral Receptive Field Modeling
tfitstrf TFITSTRF: Temporal Receptive Field Modeling